const projectsObject = [
  {
    id: 1,
    categor: "Veb sayt",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item1.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 2,
    categor: "SMM",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item2.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 3,
    categor: "Veb dizayn",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item3.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 4,
    categor: "Veb sayt",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item4.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 5,
    categor: "SMM",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item5.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 6,
    categor: "Veb dizayn",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item6.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 7,
    categor: "Veb sayt",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item1.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 8,
    categor: "SMM",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item2.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 9,
    categor: "Mobil ilova",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item3.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 10,
    categor: "Veb dizayn",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item4.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 11,
    categor: "SMM",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item5.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
  {
    id: 12,
    categor: "Mobil ilova",
    name: 'UYMAKON mobil ilovasi',
    img: "../assets/images/projects/item6.png",
    icon: "../assets/images/projects/hover-icon.svg",
  },
]
export default projectsObject